### ISSUE TITLE
Question about tbman_free?

### ISSUE THREAD

**Issue by haifenghuang** [johsteffens/tbman#2]
As your readme said:

```c
int main( int argc, char* argv[] )
{
   tbman_open();
   
   ... // my program
   
   tbman_close();
   return my_exit_state;
}
```

Between `tbman_open()` and `tbman_close()`, if I'm using `tbman_malloc` or `tbman_realloc`, do I need to call `tbman_free`? if not, will it be any memory leak?

**Comment by johsteffens** [comment]
Yes, it would be a memory leak as far as coding hygiene is concerned.
However, your question apparently implies: "Can I rely on a tool like valgrind detecting that leak?". Here you raise a very good point: Since valgrind only analyzes interaction of your program with the system and not interaction with tbman, it would not detect leaks for allocations tbman holds in its memory pools. I've added a description and workaround in [Side effects](https://github.com/johsteffens/tbman#leak-detection).

Hope that helps.

Johannes

**Comment by haifenghuang** [comment]
Thanks a lot for the Explanation.
