### ISSUE TITLE
Constant Magic number in token_manager_s_create function

### ISSUE THREAD

**Issue by SuppenSeebi** [johsteffens/tbman#3]
Changing the default configuration to:
`static const size_t default_pool_size       = 0x100000; // before 0x10000`
and
`static const size_t default_max_block_size = 1024 * 64 - 1; // before 0x1024 * 16`
resulted in the error message of line 142 in _token_manager_s_create_ of tbman.c while huge allocations where processed (for more info see below):
`if( stack_size > 0x10000 ) ERR( "stack_size %u exceeds 0x10000", stack_size );`
Has this magic number a particular meaning or is it more likely that it is supposed to be equal to the default_pool_size?
I stumbled upon this while I tried to evaluate the performance of your memory manager and others. For the context: I have several tests, where one is a simulation of a huge amount of random access mallocs/frees (4kB - 65kB allocations).  This is why I tried to increase the configuration a bit, which finally resulted into the error message stated above.

Is this _0x10000_magic number wanted or must it be equal to _default_pool_size_?

**Comment by johsteffens** [comment]
Hi SuppenSeebi, thanks for using tbman.

The values for 'default_pool_size', 'default_min_block_size', 'default_max_block_size' must each be be a power of 2. 
(General design reasons.)

(default_pool_size/default_min_block_size) must stay below 0x10000. 
That is because tbman uses 16bit tokens to address individual blocks in a pool.

Currently, the maximum allowed number of 'default_pool_size' would therefore be 0x40000.
If you want a higher value, increase default_min_block_size along with it. Beware, though, that this gives you extra overhead for small allocations. 

'default_max_block_size' should be somewhat smaller than default_pool_size for efficiency reasons. 
I'd recommend at least a factor 4 smaller.

Hope that helps

Johannes

**Comment by SuppenSeebi** [comment]
That helped very well. Just to be sure about the mechanism:
There are multiple pools of memory. Each containing multiple blocks, which indicate a different fixed default size (between _default_min_block_size_ and _default_max_block_size_). Each block contains a array of tokens, each sorted by their state (full, free and empty).
The reason for _(default_pool_size/default_min_block_size) < 0x10000_ is to organize the blocks with 16 bit tokens. The token managers themselves are organized under the memory manager as a binary tree, such that O(n*log(n)) is achieved for traversing for a token manager with a desired memory address. These are inside the _internal_btree_. Anything in particular that I missed/got wrong? If not we can close this issue.

Thank you for your patience and your great work!

**Comment by johsteffens** [comment]
You've got it right!

Just to be clear on access-complexity:

A single alloc/free/realloc maximally accesses one node, which is O(log(n)). Traversing the entire tree would be O(n*log(n)), as you said.

For size <= max_block_size [with size communicated](https://github.com/johsteffens/tbman#anchor_faster_collection), you have mostly just O(1) complexity because the tree is bypassed.

best wishes
